/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-06-06 19:32:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1496741806463L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/IoT/Java/GitRepository/TestRepository/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PhotoBoard/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/IoT/Java/GitRepository/TestRepository/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PhotoBoard/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\r\n");
      out.write("        <title>PhotoBoard</title>\r\n");
      out.write("        <link href=\"");
      out.print(application.getContextPath());
      out.write("/resources/bootstrap-3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/jquery/jquery-3.2.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(application.getContextPath());
      out.write("/resources/bootstrap-3.3.7/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        function handleBtnUpdate(bnum){\r\n");
      out.write("    \t\tvar bpassword = $(\"#bpassword\").val();\r\n");
      out.write("    \t\tif(bpassword == \"\"){\r\n");
      out.write("    \t\t\t$(\"#bpassword\").attr(\"placeholder\" , \"비밀번호를 입력하셔야 합니다.\");\r\n");
      out.write("    \t\t\t$(\"#bpassword\").css(\"border-color\",\"red\");\r\n");
      out.write("    \t\t\treturn;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("    \t\t\turl: \"checkBpassword\",\r\n");
      out.write("    \t\t\tmethod: \"post\",\r\n");
      out.write("    \t\t\t//data: \"bno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&bpassword=\"+bpassword\r\n");
      out.write("    \t\t\tdata: {\"bno\":bnum, \"bpassword\":bpassword},\r\n");
      out.write("    \t\t\tsuccess: function(data){\r\n");
      out.write("    \t\t\t\tif(data.result == \"success\"){\r\n");
      out.write("    \t\t\t\t\tlocation.href=\"update?bno=\"+bnum;\r\n");
      out.write("    \t\t\t\t} else{\r\n");
      out.write("    \t\t\t\t\t$(\"#bpassword\").val(\"\");\r\n");
      out.write("    \t\t\t\t\t$(\"#bpassword\").attr(\"placeholder\" , \"비밀번호가 다릅니다.\");\r\n");
      out.write("            \t\t\t$(\"#bpassword\").css(\"border-color\",\"red\");\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t}\r\n");
      out.write("        \t    \t\r\n");
      out.write("        \tfunction handleBtnDelete(bnum){\r\n");
      out.write("        \t\tvar bpassword = $(\"#bpassword\").val();\r\n");
      out.write("        \t\tif(bpassword == \"\"){\r\n");
      out.write("        \t\t\t$(\"#bpassword\").attr(\"placeholder\" , \"비밀번호를 입력하셔야 합니다.\");\r\n");
      out.write("        \t\t\t$(\"#bpassword\").css(\"border-color\",\"red\");\r\n");
      out.write("        \t\t\treturn;\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t\t$.ajax({\r\n");
      out.write("        \t\t\turl: \"checkBpassword\",\r\n");
      out.write("        \t\t\tmethod: \"post\",\r\n");
      out.write("        \t\t\tdata: {\"bno\":bnum, \"bpassword\":bpassword},\r\n");
      out.write("        \t\t\tsuccess: function(data){\r\n");
      out.write("        \t\t\t\tif(data.result == \"success\"){\r\n");
      out.write("        \t\t\t\t\tlocation.href=\"delete?bno=\"+bnum;\r\n");
      out.write("        \t\t\t\t} else{\r\n");
      out.write("        \t\t\t\t\t$(\"#bpassword\").val(\"\");\r\n");
      out.write("        \t\t\t\t\t$(\"#bpassword\").attr(\"placeholder\" , \"비밀번호가 다릅니다.\");\r\n");
      out.write("                \t\t\t$(\"#bpassword\").css(\"border-color\",\"red\");\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t})\r\n");
      out.write("        \t}\r\n");
      out.write("        \t$('.modal').on('hidden.bs.modal', function (e) {\r\n");
      out.write("        \t    console.log('modal close');\r\n");
      out.write("        \t  $(this).find('form')[0].reset()\r\n");
      out.write("        \t});\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div align=\"center\" style=\"padding:10px; font-weight:bold; font-size:30px\">\r\n");
      out.write("\t\tPhotoBoard\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\t<div align=\"right\">\r\n");
      out.write("\t\t<a href=\"write\" class=\"btn btn-default\" style=\"margin:5px 30px\">Upload</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<div align=\"right\">\r\n");
      out.write("\t\t<a href=\"write\" class=\"btn btn-default\" style=\"margin:5px 30px\">Upload</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/list.jsp(74,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("b");
      // /WEB-INF/views/list.jsp(74,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/list.jsp(74,8) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        \t<div style=\"position:relative; border:solid 1px #BDBDBD; width:751px; margin: 30px auto;\" >\r\n");
            out.write("        \t\r\n");
            out.write("        \t<div style=\"font-weight:bold; font-size:18px; width:750px; height:55px; padding:15px;\">\r\n");
            out.write("            \t<span class=\"glyphicon glyphicon-user\" style=\"width:10px; height:10px;\"></span>&nbsp; ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.bwriter }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div> \r\n");
            out.write("        \t<div><img src=\"file?bno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"750px\"/></div>\r\n");
            out.write("        \t<div style=\"margin:10px;\">\r\n");
            out.write("        \t\t<a type=\"button\" class=\"btn btn-default\" href=\"hit?bno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("        \t\t\t<span class=\"glyphicon glyphicon-heart-empty\"></span>\r\n");
            out.write("        \t\t</a>\r\n");
            out.write("        \t\t<!-- 수정 modal 띄우기 -->\r\n");
            out.write("        \t\t<button type=\"button\" class=\"btn btn-default\" data-target=\"#layerpop1\" data-toggle=\"modal\">\r\n");
            out.write("        \t\t\t<span class=\"glyphicon glyphicon-pencil\"></span>\r\n");
            out.write("        \t\t</button>\r\n");
            out.write("        \t\t<div class=\"modal fade\" id=\"layerpop1\" >\r\n");
            out.write("\t\t\t\t  <div class=\"modal-dialog\">\r\n");
            out.write("\t\t\t\t    <div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t      <!-- header -->\r\n");
            out.write("\t\t\t\t      <div class=\"modal-header\">\r\n");
            out.write("\t\t\t\t        <!-- 닫기(x) 버튼 -->\r\n");
            out.write("\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
            out.write("\t\t\t\t        <!-- header title -->\r\n");
            out.write("\t\t\t\t        <h4 class=\"modal-title\">수정을 위해 비밀번호를 입력하세요.</h4>\r\n");
            out.write("\t\t\t\t      </div>\r\n");
            out.write("\t\t\t\t      <!-- body -->\r\n");
            out.write("\t\t\t\t      <div class=\"modal-body\">\r\n");
            out.write("\t\t\t\t            <div class=\"form-group\">\r\n");
            out.write("\t\t\t\t                <div class=\"input-group\">\r\n");
            out.write("\t\t\t\t                    <span class=\"input-group-addon\">\r\n");
            out.write("\t\t\t\t                        <span class=\"glyphicon glyphicon-lock\"></span>\r\n");
            out.write("\t\t\t\t                    </span>\r\n");
            out.write("\t\t\t\t                    <input id=\"bpassword\" type=\"password\" class=\"form-control\" placeholder=\"비밀번호\" name=\"bpassword\" />\r\n");
            out.write("\t\t\t\t                </div>\r\n");
            out.write("\t\t\t\t            </div>\r\n");
            out.write("\t\t\t\t      </div>\r\n");
            out.write("\t\t\t\t        <input type=\"button\" class=\"btn btn-default\" onclick=\"handleBtnUpdate(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\" value=\"입력\"/>\r\n");
            out.write("\t\t\t\t        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
            out.write("\t\t\t\t      </div>\r\n");
            out.write("\t\t\t\t    </div>\r\n");
            out.write("\t\t\t\t  </div>\r\n");
            out.write("\t\t\t\t<!-- 삭제 modal -->\r\n");
            out.write("        \t\t<button type=\"button\" class=\"btn btn-default\" data-target=\"#layerpop2\" data-toggle=\"modal\">\r\n");
            out.write("        \t\t\t<span class=\"glyphicon glyphicon-remove\"></span>\r\n");
            out.write("        \t\t</button>\r\n");
            out.write("        \t\t<div class=\"modal fade\" id=\"layerpop2\" >\r\n");
            out.write("\t\t\t\t  <div class=\"modal-dialog\">\r\n");
            out.write("\t\t\t\t    <div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t      <!-- header -->\r\n");
            out.write("\t\t\t\t      <div class=\"modal-header\">\r\n");
            out.write("\t\t\t\t        <!-- 닫기(x) 버튼 -->\r\n");
            out.write("\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
            out.write("\t\t\t\t        <!-- header title -->\r\n");
            out.write("\t\t\t\t        <h4 class=\"modal-title\">삭제를 위해 비밀번호를 입력하세요.</h4>\r\n");
            out.write("\t\t\t\t      </div>\r\n");
            out.write("\t\t\t\t      <!-- body -->\r\n");
            out.write("\t\t\t\t      <div class=\"modal-body\">\r\n");
            out.write("\t\t\t\t            <div class=\"form-group\">\r\n");
            out.write("\t\t\t\t                <div class=\"input-group\">\r\n");
            out.write("\t\t\t\t                    <span class=\"input-group-addon\">\r\n");
            out.write("\t\t\t\t                        <span class=\"glyphicon glyphicon-lock\"></span>\r\n");
            out.write("\t\t\t\t                    </span>\r\n");
            out.write("\t\t\t\t                    <input id=\"bpassword\" type=\"password\" class=\"form-control\" placeholder=\"비밀번호\" name=\"bpassword\" />\r\n");
            out.write("\t\t\t\t                </div>\r\n");
            out.write("\t\t\t\t            </div>\r\n");
            out.write("\t\t\t\t      </div>\r\n");
            out.write("\t\t\t\t        <input type=\"button\" class=\"btn btn-default\" onclick=\"handleBtnDelete(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\" value=\"입력\"/>\r\n");
            out.write("\t\t\t\t        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
            out.write("\t\t\t\t      </div>\r\n");
            out.write("\t\t\t\t    </div>\r\n");
            out.write("\t\t\t\t  </div>\r\n");
            out.write("        \t<div style=\"font-weight:bold; font-size: 15px; padding:0px 0px 5px 10px; margin:10px 0px 0px 0px\">hit ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.bhitcount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("        \t<div style=\"font-weight:bold; font-size: 15px; padding:0px 0px 5px 10px\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.btitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("        \t<div style=\"padding:0px 0px 5px 10px\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.bcontent }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("        \t<div style=\"font-size:10px; color: #8C8C8C; padding:0px 0px 0px 10px\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.bdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("        \t</div>\r\n");
            out.write("        \t</div>\r\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
